# Generated by Django 3.2.3 on 2021-06-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(verbose_name='Date Added')),
                ('input_text', models.TextField(verbose_name='Text')),
                ('language', models.CharField(max_length=120, verbose_name='Language')),
                ('output_text', models.TextField(blank=True, verbose_name='Remarks')),
            ],
        ),
    ]
