# Generated by Django 3.2.3 on 2021-06-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_entry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
    ]
